import type { Project } from "../types";

import tableauDashbord from "@/assets/projects/ecommerce-data-analysis/ecommerce_dap.png";

export const eCommerceDataAnalysis = {
  id: "e-commerce-data-analysis",

  title: {
    en: "E-Commerce Sales Performance Analysis",
    fr: "Analyse de Performance E-Commerce",
  },

  company: "Solo",
  role: {
    en: "Personal Data Project",
    fr: "Projet Data Personnel",
  },

  track: ["data"],
  industry: "retail",
  productType: "analysis",

  technologies: ["python", "postgresql", "sql", "tableau"],
  skills: ["data-analysis", "data-modeling", "etl", "dashboarding", "process-optimization"],

  metrics: {
    hoursInvested: 20,
    context: {
      label: {
        en: "Revenue Analyzed",
        fr: "Chiffre d'Affaires Analysé",
      },
      value: 941786,
      unit: {
        en: "$",
        fr: "$",
      },
    },
  },

  systemsBuilt: [
    {
      en: "Python raw data ingestion workflow",
      fr: "Workflow d'ingestion des données brutes avec Python",
    },
    {
      en: "SQL cleaning, transformation and analytics layer",
      fr: "Couche SQL de nettoyage, transformation et analyse",
    },
    {
      en: "Dimensional model with sales facts and date attributes",
      fr: "Modèle dimensionnel avec faits de ventes et attributs calendaires",
    },
    {
      en: "Analytical SQL views for revenue, product mix, fulfillment and cancellation analysis",
      fr: "Vues SQL analytiques pour l'analyse du chiffre d'affaires, du mix produit, du fulfillment et des annulations",
    },
    {
      en: "Interactive Tableau dashboard for sales performance exploration",
      fr: "Dashboard Tableau interactif pour explorer la performance des ventes",
    },
  ],

  summary: {
    en: "End-to-end e-commerce analytics project combining Python ingestion, SQL modeling and Tableau visualization to identify revenue drivers, catalog risks and operational inefficiencies.",
    fr: "Projet d'analyse e-commerce de bout en bout combinant ingestion Python, modélisation SQL et visualisation Tableau afin d'identifier les leviers de chiffre d'affaires, les risques catalogue et les inefficiences opérationnelles.",
  },

  problem: {
    en: "The raw sales dataset contained transactional information across orders, products, categories and fulfillment methods, but required cleaning, modeling and analysis to reveal actionable business insights.",
    fr: "Le jeu de données brut contenait des informations transactionnelles sur les commandes, produits, catégories et modes de fulfillment, mais nécessitait nettoyage, modélisation et analyse pour faire émerger des insights exploitables.",
  },

  solution: {
    en: "Built a structured analytics workflow using Python for ingestion, SQL for cleaning and transformation, analytical views for business questions, and Tableau for interactive reporting.",
    fr: "Construction d'un workflow analytique structuré avec Python pour l'ingestion, SQL pour le nettoyage et la transformation, des vues analytiques pour les questions métier et Tableau pour le reporting interactif.",
  },

  impact: [
    {
      en: "Analyzed more than 103,000 orders, 110,000 items sold and $941K in revenue across a public e-commerce dataset.",
      fr: "Analyse de plus de 103 000 commandes, 110 000 articles vendus et 941 K$ de chiffre d'affaires sur un jeu de données e-commerce public.",
    },
    {
      en: "Identified a strong catalog concentration risk, with nearly 80% of revenue generated by the top three product categories.",
      fr: "Identification d'un risque fort de concentration catalogue, avec près de 80% du chiffre d'affaires généré par les trois principales catégories produit.",
    },
    {
      en: "Highlighted $90K in cancellation-related revenue leakage and a 36% higher cancellation risk on merchant-fulfilled orders.",
      fr: "Mise en évidence de 90 K$ de chiffre d'affaires perdu lié aux annulations et d'un risque d'annulation 36% plus élevé sur les commandes gérées par les vendeurs tiers.",
    },
    {
      en: "Built a Tableau dashboard to explore sales trends, product mix, fulfillment performance and cancellation impact.",
      fr: "Création d'un dashboard Tableau pour explorer les tendances de ventes, le mix produit, la performance du fulfillment et l'impact des annulations.",
    },
  ],

  screenshots: [
    {
      src: tableauDashbord,
      alt: {
        en: "Tableau interactive dashboard",
        fr: "Dashboard interactif Tableau",
      },
    },
  ],

  links: {
    github: "https://github.com/luneroka/sql_dap_ecommerce",
  },

  period: {
    en: "April 2026",
    fr: "Avril 2026",
  },

  featured: true,
} satisfies Project;
